//// <auto-generated />
//using System;
//using ConsoleApp;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace ConsoleApp.Migrations
//{
//    [DbContext(typeof(BloggingContext))]
//    partial class BloggingContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.1.2")
//                .HasAnnotation("Relational:MaxIdentifierLength", 64);

//            modelBuilder.Entity("ConsoleApp.Blog", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("char(36)");

//                    b.Property<DateTime>("CreateTime")
//                        .HasColumnType("datetime(6)");

//                    b.Property<uint>("Rating")
//                        .HasColumnType("int unsigned");

//                    b.Property<string>("Url")
//                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
//                        .HasMaxLength(50);

//                    b.HasKey("Id", "CreateTime");

//                    b.HasIndex("CreateTime");

//                    b.ToTable("Blog");
//                });

//            modelBuilder.Entity("ConsoleApp.Post", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("char(36)");

//                    b.Property<Guid>("BlogId")
//                        .HasColumnType("char(36)");

//                    b.Property<string>("Content")
//                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
//                        .HasMaxLength(50);

//                    b.Property<DateTime>("CreateTime")
//                        .HasColumnType("datetime(6)");

//                    b.Property<string>("Title")
//                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
//                        .HasMaxLength(50);

//                    b.HasKey("Id");

//                    b.HasIndex("BlogId");

//                    b.ToTable("Post");
//                });

//            modelBuilder.Entity("ConsoleApp.Post", b =>
//                {
//                    b.HasOne("ConsoleApp.Blog", "Blog")
//                        .WithMany("Posts")
//                        .HasForeignKey("BlogId")
//                        .HasPrincipalKey("Id")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
